name: join_me
description: An app to join your friends !
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  google_maps_flutter: ^0.5.23+1
  provider: ^4.0.4
  http: ^0.12.0+4
  rive: ^0.0.1
  contacts_service: ^0.3.10
  permission_handler: '^4.3.0'
  geolocator: ^5.1.4+2
  image_picker: ^0.6.3+4
  url_launcher: ^5.2.5

  cupertino_icons: ^0.1.2
  touchable_opacity: 1.0.1

  firebase_core: 0.4.4
  firebase_auth: 0.15.3
  firebase_messaging: ^6.0.12
  cloud_firestore: ^0.13.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
